### ISSUE TITLE
Server Crash on connnect after installing ServerExtension

### ISSUE THREAD

**Issue by morthuber** [ForrestMarkX/KF2-Server-Extension#14]
### Details
Version: 0.99
KF Server Version: 10897
[Launch.log](https://github.com/ForrestMarkX/KF2-Server-Extension/files/1432589/Launch.log)

### What happens:
After installing the Mod on the dedicated Server and the Client, I start the Server using ?Mutator=ServerExtMut.ServerExtMut 

Server starts up normally (see: Launch.log) and the web admin page is available after a few seconds, keeps running, if I do nothing. As soon as I connect from my client the server dies, the only Error I get is:
Error: Failed to read file '../../KFGame/Script/U_0x011000010557FF9B.usa' error ()

If I read the Log correctly ../../KFGame/Script/ relative from the base directory is the KFGame/Script directory of the Server. Which is empty except for a "Manifest.txt" file. I'm assuming the file should be created automatically, since it contains a user id and was not in the downloaded .zip?

Reinstalling the KF2 Server with steamcmd and reinstalling the mod did not help. The Server works fine, when I disable the mod. I have found nothing I did wron in the last hours of debugging, does anyone have an idea?

### Steps to reproduce
* Install KF2 Server using steamcmd
* Install Server Extension following Install instructions from "ServerExtReadme.txt" (and also copy xVoteAnnouncer.upk to <Root folder>/KillingFloor2/KFGame/BrewedPC/)
* enable web admin (I just do that for debugging / connectivity testing)
* Install Server Extension on my client manually (so no download is required)
* start KF2 server (with the mutator)
* connect from client

**Comment by ForrestMarkX** [comment]
Your KF2 server install seems to be corrupted

**Comment by morthuber** [comment]
Thought so too, that's why I reinstalled to a different directory. Is there a way to get more information (as to why it can't access / create that file) that could help me debug this?

**Comment by ForrestMarkX** [comment]
That's a default thing that happens with everyones ServerExt install

**Comment by morthuber** [comment]
> That's a default thing that happens with everyones ServerExt install

Sorry for sounding like an idiot here, but which part happens with everyone's Install? The KF2 corruption? If so: Would that be a bug, or just something I failed to do that would fix the corrupt install?

**Comment by ForrestMarkX** [comment]
No this line you mentioned "Error: Failed to read file '../../KFGame/Script/U_0x011000010557FF9B.usa' error ()"

**Comment by morthuber** [comment]
Turns out I pulled the wrong version if the ServerExtension Mod (the last version before you took over).
Sorry for wasting your time...
