### ISSUE TITLE
Boss Wave Bugged

### ISSUE THREAD

**Issue by axolotl777** [ForrestMarkX/KF2-Server-Extension#18]
The camera is stuck in a third person view of the boss and doesn't return to the player, making the last wave virtually un-winnable.

**Comment by robertoocpgammes1** [comment]
I'm also having this problem my friend.
[http://prntscr.com/hfforo](url)

**Comment by ForrestMarkX** [comment]
There's the problem, you're spawning two bosses

**Comment by robertoocpgammes1** [comment]
Thanks for the answer Forrest.
As I do just 1 boos on the last wave, I've tried several configurations but always end up coming 2 the same way.

**Comment by robertoocpgammes1** [comment]
Thanks for the reply, Forrest.
I tried to put only 1 boss on the last wave, tried various configurations, but always ends up coming 2 bosses in the end.
Sorry for the lousy English

**Comment by duk6046** [comment]
This is my boss camera fix code, add in ExtPlayerController.uc
it becomes similar to existing KF2 client.

function SetBossCamera( KFInterface_MonsterBoss Boss )
{
	if( Boss != none && Boss.GetMonsterPawn().HitFxInfo.bObliterated )
	{
		SetLocation( Boss.GetMonsterPawn().Location );
	}

	SetViewTarget( Boss.GetMonsterPawn() );

	if( Role == ROLE_Authority && !IsLocalPlayerController() )
	{
		PlayerCamera.CameraStyle = 'Boss';
	}
	else
	{
		ClientSetCameraMode( 'Boss' );
	}
	SetTimer(3.0, false, 'ResetCamera');
}

function ResetCamera()
{
    local ExtPlayerController KFPC;

    foreach WorldInfo.AllControllers(class'ServerExt.ExtPlayerController', KFPC)
    {
       KFPC.SetCameraMode('FirstPerson');
       KFPC.ClientSetCameraMode('FirstPerson');
    }
}

**Comment by robertoocpgammes1** [comment]
Could you check your ExtPlayerController.uc?

**Comment by robertoocpgammes1** [comment]
Problem solved:

function SetBossCamera( KFInterface_MonsterBoss Boss )
{
    // If our view target has been obliterated, the camera will default to view the player controller.
    // So, put the player controller where the view target was.
    if( Boss != none && Boss.GetMonsterPawn().HitFxInfo.bObliterated )
    {
        SetLocation( Boss.GetMonsterPawn().Location );
    }

    SetViewTarget( Boss.GetMonsterPawn() );

    if( Role == ROLE_Authority && !IsLocalPlayerController() )
    {
        PlayerCamera.CameraStyle = 'Boss';
    }
    else
    {
        ClientSetCameraMode( 'Boss' );
    }
}
