### ISSUE TITLE
Explosions deal no radial/blast damage.

### ISSUE THREAD

**Issue by XKirby** [ForrestMarkX/KF2-Server-Extension#19]
### Details
As the title says, all explosions for the Demolitionist, except for grenades, deal no blast damage. They only deal contact damage.

### Screenshots
I don't have a screenshot, but the logs in the server said something about the world getting hit and misreading a damage type because of it. Here's what showed up:

```
ScriptWarning: GetLastHitByDamageType() Received non-KFDamageType damagetype: DamageType
	KFGameInfo_Survival KF-BIOTICSLAB.TheWorld:PersistentLevel.KFGameInfo_Survival_0
	Function KFGame.KFGameInfo:GetLastHitByDamageType:022D
```

### Steps to reproduce
Fire anything that deals blast damage to an enemy and watch it do almost nothing.

**Comment by ForrestMarkX** [comment]
Fixed by commit d4403a970ba22fc5c794b7d9e4cd3011c0b3758d
