### ISSUE TITLE
multi language support?

### ISSUE THREAD

**Issue by JJPandari** [ForrestMarkX/KF2-Server-Extension#21]
If we can have multi lang in this mod, it would really help expanding player base of this great mod. Specifically, I'm looking for CJK(Chinese) support. I'll do the translation myself or with some other local players if this can be implemented.  

I see that currently CJK can be shown as player's ID over one's head, in the chat, etc., so the game supports unicode, but they won't show on the mod-added scoreboard, not sure if it is easy to implement :/

**Comment by ForrestMarkX** [comment]
Not possible to do because the font does not support Korean, Russian, Japanese and Chinese
