### ISSUE TITLE
Camera got stucked in boss wave.

### ISSUE THREAD

**Issue by death-wrath** [ForrestMarkX/KF2-Server-Extension#22]
The Health HUD bar appeared before the cutscene ended. Then, some people's camera would get stucked on boss, while they could move around normally. I noticed that melee-ing would not deal damage either. This seems to happen for some people only (not all players in server). I subscribed to workshop item, did that version fix this problem or I have to download this github version instead ?

**Comment by ForrestMarkX** [comment]
Duplicate of https://github.com/ForrestMarkX/KF2-Server-Extension/issues/18
