### ISSUE TITLE
The melle attack doesn´t work if an enemy (for example Cyst) hold you

### ISSUE THREAD

**Issue by Axel2k** [ForrestMarkX/KF2-Server-Extension#25]
Hello,

when using this mod the following occurs:

If an enemy hold you an the game says "Press Button" for example "V" for melee attack nothing happens you stuck and die. I tried the Button without being hold from the zombies and the melee attack works normal.

Without the Server Extension everthing works fine.

Gamversion 1059 Crampus Christmas.

Is this a Bug or can it be set up so that the melee attack is working with the Server Extension?

By
Axel

**Comment by Pirotehnik13** [comment]
try recompile mutator on new version editor. It helped me

**Comment by Axel2k** [comment]
Thank you for the Information. Is there a quick manual/way how to recomplie the mutator because i haven´t any experience in complie a mutator for my own ;)
What do i need?

**Comment by Pirotehnik13** [comment]
https://forums.tripwireinteractive.com/forum/killing-floor-2/killing-floor-2-modifications/code/110487-guide-compiling-stuff-a-general-howto-before-official-support-is-released

**Comment by HickDead** [comment]
Here is a guide that is more up to date: http://steamcommunity.com/sharedfiles/filedetails/?id=1112644122

**Comment by Axel2k** [comment]
Ok thank you. 
When do you plan to official release a recompiled mutator on V1059?

You wrote "It helped me": Do you have the mutator recomplied / working
for now and can you post it or send it to me?

I see that you have to do a few steps to recompile the mutator and haven´t done this before...
