### ISSUE TITLE
DemoAOE ISSUE

### ISSUE THREAD

**Issue by Gleemax** [ForrestMarkX/KF2-Server-Extension#29]
### Details
# **DemoAOE ISSUE:**
You **MUST** have at least **one** point of **DemoAOE**
to set **_Ext_PerkDemolition(Perk).AOEMult_** to more than 0.
The performance is if you have no such skill, you **cant dealt explosive damage**

### Steps to reproduce
# **DemoAOE ISSUE:**
**Ext_PerkDemolition.uc**
set initial **_AOEMult_** value as 1.0f

Thanks

**Comment by ForrestMarkX** [comment]
Fixed by fd568e3d6607f2488752d3bb7edd452b825f2987
