### ISSUE TITLE
Survivalist issues

### ISSUE THREAD

**Issue by Pirotehnik13** [ForrestMarkX/KF2-Server-Extension#4]
Survivalist weapon Traits (such as Damage, rate, reload and othes) don't work. Weapon work as standart.

**P.S.** I partially solved this problem in my last update mutator for version 1055 as follows:
1. in Ext_PerkBase.uc delete word "final" in function 
`simulated final function bool IsWeaponOnPerk( KFWeapon W )`

2. in Ext_PerkSurvivalist:
```
simulated function bool IsWeaponOnPerk( KFWeapon W )
{
	return (class'KFPerk_Demolitionist'.static.IsWeaponOnPerk( W,, class'KFPerk_Demolitionist' ) ||
				class'KFPerk_Support'.static.IsWeaponOnPerk( W,, class'KFPerk_Support' ) ||
				class'KFPerk_Sharpshooter'.static.IsWeaponOnPerk( W,, class'KFPerk_Sharpshooter' ) || 
				class'KFPerk_Commando'.static.IsWeaponOnPerk( W,, class'KFPerk_Commando' ) ||
				class'KFPerk_Gunslinger'.static.IsWeaponOnPerk( W,, class'KFPerk_Gunslinger' ) ||
				class'KFPerk_Berserker'.static.IsWeaponOnPerk( W,, class'KFPerk_Berserker' ) ||
				class'KFPerk_SWAT'.static.IsWeaponOnPerk( W,, class'KFPerk_SWAT' ) ||
				class'KFPerk_FieldMedic'.static.IsWeaponOnPerk( W,, class'KFPerk_FieldMedic' ));
}
```

but I'm not sure is this right. Survivalist's trait Auto-fire still not working.
I hope it will be useful

**Comment by ForrestMarkX** [comment]
Fixed by commit 0c48a21147421a6931793491af068c525c3a855a
