### ISSUE TITLE
Rack'em up could get more than maxheadshot hits.

### ISSUE THREAD

**Issue by oh1no** [ForrestMarkX/KF2-Server-Extension#8]
the maxhits should be 27,but on hud it can go up to more than 50.

**Comment by FreebaseJosh** [comment]
Current Max is 255;

You can change this yourself by doing the following steps:
1. Open Ext_PerkRhythmPerkBase.uc
3. Search for 255
3. Change the number to anything lower than 255 [Ex. 27] (Anything higher than 255 will not work)

Before: HeadShotComboCount = Min(HeadShotComboCount+1,255);
After: HeadShotComboCount = Min(HeadShotComboCount+1,27);

**Comment by oh1no** [comment]
wait so Rack 'em up trait's level has no effect,since maxcombo is always 255 no matter you are level 1 or 5?
