### ISSUE TITLE
When spectator, change to 1st person from 3rd person itself continuously 

### ISSUE THREAD

**Issue by duk6046** [ForrestMarkX/KF2-Server-Extension#9]
pls fix this

**Comment by duk6046** [comment]
maybe occurs specific situation...

**Comment by duk6046** [comment]
um.. sry to bad English

**Comment by duk6046** [comment]
I'm sorry, it is no bug... The cause was other boss camera fix code

**Comment by FreebaseJosh** [comment]
Really? Which piece of code was causing the issue?

**Comment by duk6046** [comment]
just talk about my server. in a hardmodeboss...
